<h2><strong>Installing packages</strong></h2>

In [1]:
!pip install torch
!pip install pandas
!pip install seaborn

<h2>Step 1: Load Dataset</h2>

In [1]:
import pandas as pd

df=pd.read_csv("./uploads/assets/score.csv")

df

,hours_studied,sleep_hours,score
0,1,7,50
1,2,6,55
2,3,6,65
3,4,5,70
4,5,5,75
5,6,3,80
6,8,3,90

<h1><strong>Step 2: Basic Analysis</strong></h1>

In [ ]:
# data stats summary
df.describe()

,hours_studied,sleep_hours,score
count,7.000000,7.000000,7.000000
mean,4.142857,5.000000,69.285714
std,2.410295,1.527525,13.972763
min,1.000000,3.000000,50.000000
25%,2.500000,4.000000,60.000000
50%,4.000000,5.000000,70.000000
75%,5.500000,6.000000,77.500000
max,8.000000,7.000000,90.000000

In [ ]:
# total null values each col
df.isnull().sum()

hours_studied    0
sleep_hours      0
score            0
dtype: int64

<h1><strong>Step 3: Visualization</strong></h1>

In [1]:
import matplotlib.pyplot as plt
plt.scatter(df["hours_studied"], df["score"])
plt.xlabel("Hours Studied")
plt.ylabel("Score")
plt.title("Study vs Score")
plt.show()

In [1]:
import seaborn as sns

sns.lineplot(x="hours_studied", y="score", data=df)
plt.title("Trend of Study vs Score")
plt.show()

<h1><strong>Step 4: Model building</strong></h1>

In [1]:
import torch
import torch.nn as nn

X = torch.tensor(df[["hours_studied", "sleep_hours"]].values, dtype=torch.float32)
y = torch.tensor(df["score"].values, dtype=torch.float32).view(-1, 1)

model = nn.Linear(2, 1)

criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# train loop
for epoch in range(200):
    pred = model(X)  
    # loss cal
    loss = criterion(pred, y)
    # clr accumulated data
    optimizer.zero_grad()
    # cal gradient , backward pass
    loss.backward()
    # updating weigths & bia (ie model parameter)
    optimizer.step()

print("Training complete")

### Diagram: de83e97f-44f7-49ed-ab41-40e941edcabe
*No visual data found for this canvas.*